### ISSUE TITLE
能否自定义属性读取类型？

### ISSUE THREAD

**Issue by why2332742172** [Glom-c/AttributeSystem#1]
能否自定义属性读取类型？
例如我有个属性是
品质: 优秀
现在好像按照读取格式读取后面的数字 无法读取字符串？
例如我写
品质: 1
可以读取到1
但是写
品质: 优秀
无法读取到优秀

**Comment by Glom-c** [comment]
可以的，不过需要脚本写ReadPattern
具体可见readme
