### ISSUE TITLE
更改插件配置里的一些设置之后导致主手的剑一直在蓄力状态

### ISSUE THREAD

**Issue by play275** [Glom-c/AttributeSystem#7]
包括主手的剑也没有办法看到,弓箭是正常蓄力的,我以为卸载插件之后可以修复这个问题，没想到依旧是处于卡住的状态

**Comment by play275** [comment]
![image](https://user-images.githubusercontent.com/104169281/167400427-cb22198e-fffc-4fb7-a6ba-7722e2c3be77.png)

**Comment by play275** [comment]
现在已经可以确定是这个插件的问题了，装上之后又能蓄力了，卸载完之后所有的剑一直卡在蓄力

**Comment by mangoOvO123** [comment]
现在解决了吗

**Comment by mangoOvO123** [comment]
> 

现在解决了吗，请问怎么解决的

**Comment by Glom-c** [comment]
1.3.0已修复，
formula.yml里 attribute-formulas.attack-speed 设置成-1(关闭攻击速度系统)，重载as，关服，删除AS
